[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 