[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
headless = true

[client]
showErrorDetails = true
caching = true
displayEnabled = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[runner]
fastReruns = true 