[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[runner]
magicEnabled = true
installTracer = true

[client]
showErrorDetails = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 